config/routes.rb
Rails.application.routes.draw do
  
  resources :links
  resources :images
  resources :posts
  resources :comments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"
end

app/models/image.rb
class Image < ApplicationRecord
  validates :text, presence: true
  has_many :comments, as: :commentable
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
    @comments = Comment.all
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:text)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Text:</strong>
    <%= image.text %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <div class="form-group mb-3">
      <%= link_to "Show this image", image %>
    </div>
  <% end %>
</div>

<div class="form-group mb-3">
  <%= link_to "New image", new_image_path %>
</div>  

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div class="form-group mb-3">
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>
</div>  

<div class="form-group mb-3">
  <%= button_to "Destroy this image", @image, method: :delete, class: 'btn btn-danger' %>
</div>

<p><i><b>Comments</b></i></p>

<div id="comments">
  <% @image.comments.each do |comment| %>
    <%= comment.content %>
    <div class="form-group mb-3">
      <%= link_to "Show this comment", comment %>
    </div>
  <% end %>
</div>

<h5>New comment</h5>

<%= form_for(Comment.new) do |f| %>

  <div class="form-group mb-3">
    <%= f.hidden_field :commentable_id, value: params["id"] %>
    <%= f.hidden_field :commentable_type, value: params["controller"].singularize.capitalize %>
    <%= f.label :content, style: 'display: block' %>
    <%= f.text_area :content, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mb-3">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>