config/routes.rb
Rails.application.routes.draw do
  
  resources :links
  resources :images
  resources :posts
  resources :comments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="m-4">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to 'Polyblog', root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav">
              <li><%= link_to 'Posts', posts_path, class: "nav-link" %></li>
              <li><%= link_to 'Images', images_path, class: "nav-link" %></li>
              <li><%= link_to 'Links', links_path, class: "nav-link" %></li>
              <li><%= link_to 'Comments', comments_path, class: "nav-link" %></li>
            </ul>

          </div>
        </div>
      </nav>
    </div> 



    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div> 
  </body>
</html>